2018-08-30 16:32:41,315 - DataBase.py[line:22] - INFO: database class is creating...
2018-08-30 16:32:41,332 - DataBase.py[line:50] - INFO: database is connecting...
2018-08-30 16:32:41,333 - DataBase.py[line:55] - INFO: select * from record_201880 where emp_id=111111 and time like '2018-80-%'
2018-08-30 16:32:41,334 - DataBase.py[line:61] - ERROR: query database exception, (1146, "Table 'facepro.record_201880' doesn't exist")
