2018-09-10 15:50:26,342 - DataBase.py[line:23] - INFO: database class is creating...
2018-09-10 15:50:26,552 - DataBase.py[line:51] - INFO: database is connecting...
2018-09-10 15:50:34,519 - DataBase.py[line:56] - INFO: select * from empinfo where Emp_id=000001
2018-09-10 15:50:34,555 - DataBase.py[line:56] - INFO: select password from empinfo where Emp_id=000001
2018-09-10 15:50:36,241 - DataBase.py[line:56] - INFO: SELECT table_name FROM information_schema.TABLES WHERE table_name ='record_201801'
2018-09-10 15:50:36,278 - DataBase.py[line:56] - INFO: select * from record_201801 where emp_id=000001
2018-09-10 15:50:36,315 - DataBase.py[line:56] - INFO: select * from except_201801 where emp_id=000001
2018-09-10 15:50:36,353 - DataBase.py[line:62] - ERROR: query database exception, (1146, "Table 'facepro.except_201801' doesn't exist")
2018-09-10 15:50:53,026 - DataBase.py[line:56] - INFO: select * from empinfo where Emp_id=000001
2018-09-10 15:50:53,062 - DataBase.py[line:56] - INFO: select password from empinfo where Emp_id=000001
2018-09-10 15:50:54,657 - DataBase.py[line:56] - INFO: SELECT table_name FROM information_schema.TABLES WHERE table_name ='record_201801'
2018-09-10 15:50:54,693 - DataBase.py[line:56] - INFO: select * from record_201801 where emp_id=000001
2018-09-10 15:50:54,730 - DataBase.py[line:56] - INFO: select * from except_201801 where emp_id=000001
2018-09-10 15:50:54,766 - DataBase.py[line:62] - ERROR: query database exception, (1146, "Table 'facepro.except_201801' doesn't exist")
